// src/music/vibes.data.js



const vibes = [
  {
    id: "teenage-dream",
    title: "Teenage Dream",
    artist: "Katy Perry",
    cover: "/images/Teenage Dream.jpg",
    audio: "/sounds/Teenage Dream.mp3",
    lyrics: "/lyrics/Teenage Dream.lrc",
    category: "English · Classics",
  },
  {
    id: "dandelions",
    title: "Dandelions",
    artist: "Ruth B",
    cover: "/images/Dandelions.png",
    audio: "/sounds/Dandelions.mp3",
    lyrics: "/lyrics/Dandelions.lrc",
    category: "English · Classics",
  },
  {
  id: "ecoute-cherie",
  title: "Écoute Chérie",
  artist: "Vendredi sur Mer",
  cover: "/images/Écoute Chérie.png",
  audio: "/sounds/Écoute Chérie.mp3",
  lyrics: "/lyrics/Écoute Chérie.lrc",
  category: "English · Classics",
},
{
  id: "apt",
  title: "APT",
  artist: "ROSE, Bruno Mars",
  cover: "/images/APT.png",
  audio: "/sounds/APT.mp3",
  lyrics: "/lyrics/APT.lrc",
  video: "/videos/APT.mp4",
  category: "English · Classics",
},
  {
  id: "titli",
  title: "Titli",
  artist: "Chinmayi Sripada & Gopi Sundar",
  cover: "/images/Titli.png",
  audio: "/sounds/Titli.mp3",
  lyrics: "/lyrics/Titli.lrc",
  category: "Bollywood",
},
{
  id: "malang",
  title: "Malang",
  artist: "Siddharth Mahadevan, Shilpa Rao",
  cover: "/images/Malang.jpeg",
  audio: "/sounds/Malang.mp3",
  lyrics: "/lyrics/Malang.lrc",
  video: "/videos/Malang.mp4",
  category: "Bollywood",
},
  {
  id: "new-york-nagaram",
  title: "New York Nagaram",
  artist: "A. R. Rahman",
  cover: "/images/New York Nagaram.png",
  audio: "/sounds/New York Nagaram.mp3",
  lyrics: "/lyrics/New York Nagaram.lrc",
  video: "/videos/New York Nagaram.mp4",
  category: "Tamil",
  },
  {
  id: "koondukkulla",
  title: "Koondukkulla",
  artist: "S. P. Balasubrahmanyam & S. Janaki",
  cover: "/images/Koondukkulla.png",
  audio: "/sounds/Koondukkulla.mp3",
  lyrics: "/lyrics/Koondukkulla.lrc",
  video: "/videos/Koondukkulla.mp4",
  category: "Tamil",
},
{
  id: "singari",
  title: "Singari",
  artist: "Pradeep Ranganathan",
  cover: "/images/Singari.png",
  audio: "/sounds/Singari.mp3",
  lyrics: "/lyrics/Singari.lrc",
  video: "/videos/Singari.mp4",
  category: "Tamil",
},
{
  id: "oorum-blood",
  title: "Oorum Blood",
  artist: "Sai Abhyankkar, Deepthi Suresh",
  cover: "/images/Oorum Blood.png",
  audio: "/sounds/Oorum Blood.mp3",
  lyrics: "/lyrics/Oorum Blood.lrc",
  video: "/videos/Oorum Blood.mp4",
  category: "Tamil",
},
];

export default vibes;